services:
  clickhouse_kafka:
    image: clickhouse/clickhouse-server:25.6
    container_name: clickhouse_kafka
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-logs:/var/log/clickhouse-server
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      #Добавил ниже настройки, чтобы не было ошибок падения kafka при запуске
      ZOOKEEPER_TICK_TIME: 2000
      # Позволяет быстрее обнаруживать падение брокера
      ZOOKEEPER_SYNC_LIMIT: 2
      # Автоочистка снапшотов (чтобы диск не забивался)
      ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: 3
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 1
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: [zookeeper]
    stop_grace_period: 1m
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
      # Ускорение timeout-а
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 6000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    # networks:
    #   - local-kafka
    depends_on: 
      - kafka
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      # - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
    ports:
      - 8081:8081
    depends_on: [zookeeper, kafka]


volumes:
  clickhouse-logs:
  clickhouse-data:
  kafka-data:
  zookeeper-data:
  zookeeper-log:
